### PR TITLE
Move jobs away from api.ci

### PR DESCRIPTION
**Pull request by hongkailiu**
/cc @petr-muller @jsztuka

### CODE REVIEW

**Review by jsztuka — APPROVED** [review]
LGTM

**Comment by jsztuka** [comment]
Let see how the checks go.

**Comment by petr-muller** [comment]
/override ci/prow/ci-operator-config 
/override ci/prow/ci-operator-config-metadata
/override ci/prow/ci-operator-registry 
/override ci/prow/generated-config
/override ci/prow/ordered-prow-config

The jobs are hanging b/c they also run on api.ci and need images there....

**Comment by petr-muller** [comment]
(I think I raced with crier there)

**Pull request merged**
